name: Greetings
# https://github.com/marketplace/actions/first-interaction

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: "Hi! thanks for your contribution! Great first issue!"
          pr-message: "## Welcome!\n\nThank you very match for your contribution.\n\nI'll get to this PR ASAP."
